service:
  name: insert-service-name-here

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: src/handler1/handler.hello
    events:
      - http:
          method: get
          path: hello
