service:
  name: insert-service-name-here

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: src/function-handlers/http/handler1/handler.post
    events:
      - http:
          method: get
          path: hello
  openAPI:
    handler: src/function-handlers/http/docs/open-api/handler.get
    events:
      - http:
          method: get
          path: /api/v1/open-api.yml
  documentationUI:
    handler: src/function-handlers/http/docs/ui/handler.get
    events:
      - http:
          method: get
          path: /api/v1/documentation
